/**
 * Cloudflare Snippets Advanced Checker
 * Support: Pagination (>50 domains), Multiple Tokens, Batch Processing
 * Author: Gemini
 */

export default {
  async fetch(request, env, ctx) {
    // 1. 获取 API Tokens
    // 支持在环境变量 CF_API_TOKEN 中填入多个 Token，使用逗号分隔
    const tokenString = env.CF_API_TOKEN;
    
    if (!tokenString) {
      return new Response("请在 Worker 设置 -> Variables 中配置环境变量: CF_API_TOKEN", { 
        status: 500, 
        headers: { "Content-Type": "text/html;charset=UTF-8" } 
      });
    }

    // 分割并清理 Token
    const tokens = tokenString.split(',').map(t => t.trim()).filter(t => t.length > 0);

    // HTML 头部
    const htmlHeader = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>CF Snippets 批量检测</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
          .status-ok { color: #059669; font-weight: 700; }
          .status-no { color: #d1d5db; }
          .status-err { color: #dc2626; }
        </style>
      </head>
      <body class="bg-gray-50 text-gray-800 font-sans p-6">
        <div class="max-w-5xl mx-auto bg-white shadow-lg rounded-xl overflow-hidden">
          <div class="p-6 border-b border-gray-100 flex justify-between items-center bg-gray-900 text-white">
            <h1 class="text-xl font-bold">Cloudflare Snippets 检测器</h1>
            <span class="text-xs bg-gray-700 px-2 py-1 rounded">V2.0 Pro</span>
          </div>
          <div class="p-0 overflow-x-auto">
    `;

    const htmlFooter = `
          </div>
          <div class="p-4 bg-gray-50 text-xs text-center text-gray-400">
            Generated by Cloudflare Workers
          </div>
        </div>
      </body>
      </html>
    `;

    let allResults = [];
    let logMessages = [];

    // 2. 遍历每个 Token 处理
    for (const token of tokens) {
      try {
        // A. 获取该 Token 下的所有 Zone (处理分页)
        const zones = await fetchAllZones(token);
        
        if (zones.length === 0) {
          continue;
        }

        // B. 分批检测 Snippets (并发控制)
        // 每次并发 10 个，避免触发限速
        const BATCH_SIZE = 10; 
        for (let i = 0; i < zones.length; i += BATCH_SIZE) {
          const batch = zones.slice(i, i + BATCH_SIZE);
          const batchResults = await Promise.all(batch.map(zone => checkSnippets(zone, token)));
          allResults = allResults.concat(batchResults);
        }

      } catch (err) {
        logMessages.push(`Token 处理出错 (结尾: ...${token.slice(-4)}): ${err.message}`);
      }
    }

    // 3. 生成表格
    let tableRows = "";
    
    if (allResults.length === 0) {
      tableRows = `<tr><td colspan="5" class="p-8 text-center text-gray-500">未找到任何域名或 API Token 无效。${logMessages.join('<br>')}</td></tr>`;
    } else {
      // 按状态排序：已开通 > 未开通
      allResults.sort((a, b) => (b.enabled === a.enabled) ? 0 : (a.enabled ? -1 : 1));

      tableRows = allResults.map(r => `
        <tr class="border-b border-gray-100 hover:bg-blue-50 transition-colors">
          <td class="py-3 px-6 text-sm font-medium text-gray-900">${r.name}</td>
          <td class="py-3 px-6 text-xs text-gray-500">${r.accountName}</td>
          <td class="py-3 px-6 text-xs text-gray-500">${r.plan}</td>
          <td class="py-3 px-6 text-xs font-mono text-gray-400">${r.zoneId}</td>
          <td class="py-3 px-6 text-sm">
            <span class="${r.enabled ? 'status-ok' : (r.error ? 'status-err' : 'status-no')}">
              ${r.msg}
            </span>
          </td>
        </tr>
      `).join("");
    }

    const tableHtml = `
      <table class="min-w-full text-left">
        <thead class="bg-gray-100 text-gray-600 uppercase text-xs tracking-wider">
          <tr>
            <th class="py-3 px-6">域名</th>
            <th class="py-3 px-6">所属账户</th>
            <th class="py-3 px-6">Plan</th>
            <th class="py-3 px-6">Zone ID (后6位)</th>
            <th class="py-3 px-6">Snippets</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
    `;

    return new Response(htmlHeader + tableHtml + htmlFooter, {
      headers: { "Content-Type": "text/html;charset=UTF-8" }
    });
  }
};

/**
 * 辅助函数：获取单个 Token 下的所有 Zone (自动分页)
 */
async function fetchAllZones(token) {
  let allZones = [];
  let page = 1;
  let totalPages = 1;

  // 循环直到取完所有页
  while (page <= totalPages) {
    try {
      const resp = await fetch(`https://api.cloudflare.com/client/v4/zones?per_page=50&page=${page}`, {
        headers: {
          "Authorization": `Bearer ${token}`,
          "Content-Type": "application/json"
        }
      });

      if (!resp.ok) break;

      const data = await resp.json();
      if (data.success) {
        allZones = allZones.concat(data.result);
        totalPages = data.result_info.total_pages; // 更新总页数信息
        page++;
      } else {
        break;
      }
    } catch (e) {
      console.error("Fetch zones error:", e);
      break;
    }
  }
  return allZones;
}

/**
 * 辅助函数：检测单个 Zone 的 Snippets 状态
 */
async function checkSnippets(zone, token) {
  const result = {
    name: zone.name,
    accountName: zone.account ? zone.account.name : '-',
    plan: zone.plan ? zone.plan.name : '-',
    zoneId: '...' + zone.id.slice(-6),
    enabled: false,
    error: false,
    msg: "Checking..."
  };

  try {
    // 请求 Snippets Rules 列表
    const resp = await fetch(`https://api.cloudflare.com/client/v4/zones/${zone.id}/snippets/rules`, {
      headers: {
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json"
      }
    });
    
    const data = await resp.json();

    if (data.success === true) {
      result.enabled = true;
      result.msg = "✅ 已开通";
    } else {
      // 通常未开通会返回 success: false 以及特定的 error code
      result.enabled = false;
      result.msg = "未开通";
    }
  } catch (e) {
    result.error = true;
    result.msg = "⚠️ API 错误";
  }

  return result;
}
